version: "3.8"
networks:
  counter-net:
    driver: bridge

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
  #   volumes:
  #     - "./backend:/usr/src/app"
  #   ports:
  #     - 5004:5000
  #   environment:
  #     - FLASK_APP=app.py
  #     - FLASK_RUN_HOST=0.0.0.0
  #   env_file: ./backend/.env
  #   restart: always
  
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hacker
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hacker_TG
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app"
      # - "/usr/src/app/node_modules"
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5004