version: "3.11"

networks:
  mynetwork:
    driver: bridge

services:
  databases:
    container_name: postgres_hacker
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: hacker
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hacker_TG
    networks:
      - mynetwork
  # pgadmin:
  #   container_name : pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ester6126@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: hacker123
  #   ports:
  #     - "5050:80"